name: Brassy

on:
  # Triggers the workflow when pull request closed (either closed
  # as non-planned, or actually approved and merged.)
  pull_request:
    types:
      - closed
    branch: main
  # Allows run of this workflow manually from the Actions tab
  # Must be merged to default before it will be available to manually run.
  workflow_dispatch:

jobs:
  brassy-notes:
    name: Brassy
    # You do not appear to be able to use variables in the "uses" field.
    uses: NRLMMD-GEOIPS/geoips_ci/.github/workflows/reusable-brassy-notes.yaml@main
    # Only run this if the pull request was merged, not just closed.
    if: github.event.pull_request.merged == true
    permissions:
      contents: write
      pull-requests: write
    secrets:
      token: ${{ secrets.GEOIPS_TOKEN }}
