name: Build & Test in Docker

on: [push, pull_request]

env:
  REGISTRY: ghcr.io
  TEST_TAG: geoips:test

jobs:
  build_push_test_docker:
    runs-on: ubuntu-latest
    # Can't write to registry without this
    permissions:
      contents: read
      packages: write
    steps:
      # Need to make repository lowercase
      - name: Make image name
        shell: bash
        run: |
          echo "IMAGE_NAME=${GITHUB_REPOSITORY,,}" >> ${GITHUB_ENV}
      - name: Setup BuildX
        uses: docker/setup-buildx-action@v2
      - name: Login to the Registry
        uses: docker/login-action@v2.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      # - name: Build and export to Docker
      #   uses: docker/build-push-action@v3
      #     with:
      #       context: .
      #       load: true
      #       tags: ${{ env.TEST_TAG }}
      # - name: Test
      #   run: |
      #     docker run --rm ${{ env.TEST_TAG }}
      - name: Build and Push image
        uses: docker/build-push-action@v3.1.0
        with:
          push: true
          tags: ghcr.io/${{ env.IMAGE_NAME }}:latest
          file: "Dockerfile.simple"
          cache-from: type=registry,ref=ghcr.io/${{ env.IMAGE_NAME }}:buildcache
          cache-to: type=registry,ref=ghcr.io/${{ env.IMAGE_NAME }}:buildcache,mode=max