name: Build docs and test locally

on:
  # Reusable workflow
  workflow_dispatch:
    secrets:
      token:
        required: true
      docker_token:
        required: true
  pull_request:
        
# Assuming the below is in the workflow for an individual repository.
# on:
#   # Triggers the workflow when pull request created and updated
#   pull_request:
#   # Allows run of this workflow manually from the Actions tab
#   workflow_dispatch:

env:
  # The path to the GeoIPS package in DOCLINTTEST images
  BASE_GEOIPS_PATH: /packages/geoips

defaults:
  run:
    shell: bash

jobs:
  # Build the base GeoIPS doclinttest image
  # This image is used in all subsequent tests
  # It is only built for the main GeoIPS package but is used by all repositories
  #
  # Within this image, the GeoIPS package is located in /packages/geoips and is
  # installed using `pip install .[doc,lint,test]`. Scripts from geoips can be called
  # from /packages/geoips.
  #
  # Note the DOCKER_IMAGE_NAME is returned from reusable-build-docker-image
  # by including it in the "outputs" listed at the top of the workflow.
  get-doclinttest-image:
    name: Get docker image
    # You do not appear to be able to use variables in this "uses" field.
    uses: NRLMMD-GEOIPS/geoips_ci/.github/workflows/reusable-build-docker-image.yaml@main
    secrets:
      token: ${{ secrets.token }}
      docker_token: ${{ secrets.docker_token }}
    permissions:
      packages: write
      contents: write

  # Set variables that should be accessible to all jobs
  get-job-flags:
    runs-on: ${{ vars.RUNNER }}
    needs: [get-doclinttest-image]
    env:
      CURR_REPO: ${{ github.event.repository.name }}
    outputs:
      # Flags for enabling/disabling various parts of the workflow
      # Default to enabled unless overridden by a repository-level variable
      CI_BUILD_SPHINX_HTML: ${{ steps.get_job_flags.outputs.CI_BUILD_SPHINX_HTML }}
      CI_BUILD_SPHINX_PDF: ${{ steps.get_job_flags.outputs.CI_BUILD_SPHINX_PDF }}
      CI_TEST_INTERFACES: ${{ steps.get_job_flags.outputs.CI_TEST_INTERFACES }}
      CI_TEST_PYTEST_SHORT: ${{ steps.get_job_flags.outputs.CI_TEST_PYTEST_SHORT }}
      # DOCKER_IMAGE_NAME is defined in the "outputs" section at the top of
      # reusable-build-docker-image
      DOCKER_IMAGE_NAME: ${{ needs.get-doclinttest-image.outputs.DOCKER_IMAGE_NAME }}
    steps:
      - name: Get job flags
        id: get_job_flags
        run: |
          # Define an array of flags and their corresponding secret values
          flags=(CI_BUILD_SPHINX_HTML \
                 CI_BUILD_SPHINX_PDF \
                 CI_TEST_INTERFACES \
                 CI_TEST_PYTEST_SHORT)
          for flag in "${flags[@]}"; do
              # Dynamically construct the variable name and access the corresponding secret
              case $flag in
                  CI_BUILD_SPHINX_HTML) val="${{ vars.CI_BUILD_SPHINX_HTML }}" ;;
                  CI_BUILD_SPHINX_PDF) val="${{ vars.CI_BUILD_SPHINX_PDF }}" ;;
                  CI_TEST_INTERFACES) val="${{ vars.CI_TEST_INTERFACES }}" ;;
                  CI_TEST_PYTEST_SHORT) val="${{ vars.CI_TEST_PYTEST_SHORT }}" ;;
              esac
              # Check if the secret value is "true" and set the environment variable and output
              if [ "$val" == "false" ]; then
                  echo "${flag}=false"
                  echo "${flag}=false" >> $GITHUB_ENV
                  echo "${flag}=false" >> $GITHUB_OUTPUT
              else
                  echo "${flag}=true"
                  echo "${flag}=true" >> $GITHUB_ENV
                  echo "${flag}=true" >> $GITHUB_OUTPUT
              fi
          done
          echo "DOCKER_IMAGE_NAME=${DOCKER_IMAGE_NAME}"
          echo "DOCKER_IMAGE_NAME=${DOCKER_IMAGE_NAME}" >> ${GITHUB_ENV}
          echo "DOCKER_IMAGE_NAME=${DOCKER_IMAGE_NAME}" >> ${GITHUB_OUTPUT}

  print-doc-test-variables:
    name: Print doc-test variables
    needs: [get-job-flags]
    # You do not appear to be able to use variables in this "uses" field.
    uses: NRLMMD-GEOIPS/geoips_ci/.github/workflows/reusable-print-variables.yaml@main
    with:
      # These are outputs defined above.  Explicitly pass them in here to track
      # what variables we have available to this workflow.
      CI_BUILD_SPHINX_HTML: ${{ needs.get-job-flags.outputs.CI_BUILD_SPHINX_HTML }}
      CI_BUILD_SPHINX_PDF: ${{ needs.get-job-flags.outputs.CI_BUILD_SPHINX_PDF }}
      CI_TEST_INTERFACES: ${{ needs.get-job-flags.outputs.CI_TEST_INTERFACES }}
      CI_TEST_PYTEST_SHORT: ${{ needs.get-job-flags.outputs.CI_TEST_PYTEST_SHORT }}

  #################################################
  # Documentation builds - requires pip installed geoips, so use container
  #################################################
  docker_build_sphinx_html:
    if: >
      ! cancelled() &&
      needs.get-job-flags.outputs.CI_BUILD_SPHINX_HTML == 'true' &&
      (needs.get-doclinttest-image.result == 'success' ||
      needs.get-doclinttest-image.result == 'skipped')
    runs-on: ${{ vars.RUNNER_DOCKERRUN || vars.RUNNER }}
    needs: [get-doclinttest-image, get-job-flags]
    container:
      image: ${{ needs.get-job-flags.outputs.DOCKER_IMAGE_NAME }}
    env:
      CURR_REPO: ${{ github.event.repository.name }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure Git safe directory
        run: git config --global --add safe.directory $PWD

      - name: Install package
        run: pip install .

      - name: Run build html
        id: build-html-docs
        run: |
          # If we are specifically "template_basic_plugin" repo, then we must use
          # my_package as the package name.  Otherwise the package name matches
          # the plugin name.
          echo "${{ needs.get-job-flags.outputs.DOCKER_IMAGE_NAME }}"
          run_on_package=$CURR_REPO
          if [[ "$CURR_REPO" == "template_basic_plugin" ]]; then
            run_on_package=my_package
          fi
          echo "Build html docs"
          # Call build_docs.sh from the geoips default branch
          # Pass in
          #   the path to the current plugin repo,
          #   the name of the current repo,
          #   "html_only" to indicate producing only html output, and
          #   the path to the docs template directory in the geoips default branch.
          python3 $BASE_GEOIPS_PATH/docs/build_docs.py \
            --geoips-docs-path $BASE_GEOIPS_PATH/docs/ \
            --force \
            --repo-path . \
            $run_on_package
          ret=$?
          if [[ "${ret##*:}" != *"0"* ]]; then
            echo "::error::Building html docs ${ret##*:}"
            exit 1
          fi
          echo "BUILT_DOCS_PATH=$PWD/build/sphinx/html" >> $GITHUB_OUTPUT
      - name: Upload HTML Docs
        if: ${{ vars.UPLOAD_GITHUB_ARTIFACTS == 'true' }}
        uses: actions/upload-artifact@v4
        with:
          name: HTML Docs
          path: ${{ steps.build-html-docs.outputs.BUILT_DOCS_PATH }}
          if-no-files-found: error

  #################################################
  # Code tests - requires pip installed geoips, so use container
  #################################################
  docker_test_interfaces:
    if: >
      ! cancelled() &&
      needs.get-job-flags.outputs.CI_TEST_INTERFACES == 'true' &&
      (needs.get-doclinttest-image.result == 'success' ||
      needs.get-doclinttest-image.result == 'skipped')
    runs-on: ${{ vars.RUNNER_DOCKERRUN || vars.RUNNER }}
    needs: [get-doclinttest-image, get-job-flags]
    container:
      image: ${{ needs.get-job-flags.outputs.DOCKER_IMAGE_NAME }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Configure Git safe directory
        run: git config --global --add safe.directory $PWD
      - name: Pip install package
        run: pip install -v -e .
      - name: create_plugin_registries
        run: create_plugin_registries
      - name: Run code check script interfaces
        run: |
          python $BASE_GEOIPS_PATH/tests/utils/test_interfaces.py
          ret=$?
          echo "::group::interface_analysis"
          echo "INTERFACES analysis of code"
          echo "${ret}"
          echo "::endgroup::"
          if [[ "${ret##*:}" != *"0"* ]]; then
            echo "::error::due to interface violations ${ret##*:}"
            exit 1
          fi

  docker_test_pytest_short:
    if: >
      ! cancelled() &&
      needs.get-job-flags.outputs.CI_TEST_PYTEST_SHORT == 'true' &&
      (needs.get-doclinttest-image.result == 'success' ||
      needs.get-doclinttest-image.result == 'skipped')
    runs-on: ${{ vars.RUNNER_DOCKERRUN || vars.RUNNER }}
    needs: [get-doclinttest-image, get-job-flags]
    container:
      image: ${{ needs.get-job-flags.outputs.DOCKER_IMAGE_NAME }}
    env:
      CURR_REPO: ${{ github.event.repository.name }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Configure Git safe directory
        run: git config --global --add safe.directory $PWD
      - name: Pip install package
        run: pip install -v -e .
      - name: create_plugin_registries
        run: create_plugin_registries
      # Run unit tests for this repo if they exist
      - name: Run pytest unit tests
        run: |
          echo "::group::pytest_unit_test"
          echo "Pytest short unit tests of ${CURR_REPO}"
          echo "which pytest"
          which pytest
          if [ ! -d "./tests/unit_tests" ]; then
            echo "No unit tests found in ${CURR_REPO}"
            exit 0
          fi
          echo "pytest -q ./tests/unit_tests"
          pytest -q ./tests/unit_tests
          ret=$?
          echo "Return code: ${ret}"
          echo "::endgroup::"
          if [[ "${ret}" != *"0"* ]]; then
            echo "::error::due to geoips repo pytest errors, return code ${ret}"
            exit 1
          fi
      - name: Run base GeoIPS pytest unit tests
        if: ${{ env.CURR_REPO != 'geoips' }}
        run: |
          echo "::group::pytest_unit_test"
          echo "Pytest short unit tests of ${CURR_REPO} using core GeoIPS tests"
          echo "which pytest"
          which pytest
          echo "pytest -q $BASE_GEOIPS_PATH/tests/unit_tests"
          pytest -q $BASE_GEOIPS_PATH/tests/unit_tests
          ret=$?
          echo "Return code: ${ret}"
          echo "::endgroup::"
          if [[ "${ret}" != *"0"* ]]; then
            echo "::error::due to geoips repo pytest errors, return code ${ret}"
            exit 1
          fi
