name: Lint

# Note we want to run linting all the time
on:
  # Triggers the workflow when pull request created and updated
  pull_request:
  # Allows run of this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  lint:
    name: Lint
    # You do not appear to be able to use variables in the "uses" field.
    uses: NRLMMD-GEOIPS/geoips_ci/.github/workflows/reusable-lint.yaml@main
    permissions:
      contents: read
    secrets:
      token: ${{ secrets.GEOIPS_TOKEN }}
